package com.serverless.DAL;


import com.amazonaws.services.dynamodbv2.AmazonDynamoDB;
import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;
import com.sun.tools.javac.comp.Todo;
import org.apache.log4j.Logger;


import java.util.HashMap;
import java.util.List;


public class TodoItem {

    private static final String TODOLIST_TABLE_NAME = System.getenv("TODO_TABLE_NAME");

    // OBJECTS REQUIRED FOR DYNAMO INTERACTIONS
    private static DynamoDBAdapter db_adapter;
    private final AmazonDynamoDB client;
    private final DynamoDBMapper mapper;
    private Logger logger = Logger.getLogger(this.getClass());


    // POJO PROPERTIES
    private String id;
    private String text;
    private boolean checked;
    private long createdAt;
    private long updatedAt;

    // THE FOLLOW GETTERS AND SETTERS ALSO HAVE DATA ANNOTATIONS FOR DYNAMO DB AND MAP TO THE RELEVANT FIELDS

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "text")
    public String getText() {
        return text;
    }
    public void setText(String text) {
        this.text = text;
    }

    @DynamoDBAttribute(attributeName = "checked")
    public boolean isChecked() {
        return checked;
    }
    public void setChecked(boolean checked) {
        this.checked = checked;
    }

    @DynamoDBAttribute(attributeName = "createdAt")
    public long getCreatedAt() {
        return createdAt;
    }
    public void setCreatedAt(long createdAt) {
        this.createdAt = createdAt;
    }

    @DynamoDBAttribute(attributeName = "updatedAt")
    public long getUpdatedAt() {
        return updatedAt;
    }
    public void setUpdatedAt(long updatedAt) {
        this.updatedAt = updatedAt;
    }

    // CONSTRUCTOR

    public TodoItem() {

        DynamoDBMapperConfig mapperConfig = DynamoDBMapperConfig.builder()
                .withTableNameOverride(new DynamoDBMapperConfig.TableNameOverride(TODOLIST_TABLE_NAME))
                .build();

        // GET DB ADAPTER
        db_adapter = DynamoDBAdapter.getInstance();
        this.client = db_adapter.getDbClient();
        // CREATE DB MAPPER
        this.mapper = db_adapter.createDbMapper(mapperConfig);
    }

    // REST METHODS HERE
    public void save(TodoItem todoItem) {
        logger.info("ToDoList - save(): " + todoItem.toString());
        // SAVE THE ACTUAL TODO ITEM INTO THE DB
        this.mapper.save(todoItem);
    }

    public void update(TodoItem todoItem){
        // SAVE THE UPDATED TODO ITEM IN THE DB
        save(todoItem);

    }


    // GETT A LIST OF ALL THE TODO LIST ITEMS FROM THE DB
    public List<TodoItem> list() {

        // CREATE A SCANNER AND SCAN FOR ITEMS IN THE DB
        DynamoDBScanExpression scanExp = new DynamoDBScanExpression();
        List<TodoItem> results = this.mapper.scan(TodoItem.class, scanExp);

        // LOOP THROUGH AND LOG FOR TESTING
        // for (TodoItem i : results) {
        //     logger.info("TodoItem - list(): " + i.toString());
        // }
        return results;

    }


    public TodoItem get(String id) {

        TodoItem todoItem = null;
        HashMap<String, AttributeValue> av = new HashMap<String, AttributeValue>();
        av.put(":v1", new AttributeValue().withS(id));

        DynamoDBQueryExpression<TodoItem> queryExp = new DynamoDBQueryExpression<TodoItem>()
                .withKeyConditionExpression("id = :v1")
                .withExpressionAttributeValues(av);

        PaginatedQueryList<TodoItem> result = this.mapper.query(TodoItem.class, queryExp);

        if (result.size() > 0) {
            todoItem = result.get(0);
            logger.info("Todo - get(): todo item - " + todoItem.toString());
        } else {
            logger.info("Todo - get(): todo item - Not Found.");
        }

        return todoItem;

    }

    public Boolean delete(String id) {
        TodoItem todoItem = null;

        // get todoitem if exists
        todoItem = get(id);
        if (todoItem != null) {
            logger.info("Todo - delete(): " + todoItem.toString());
            this.mapper.delete(todoItem);
        } else {
            logger.info("ToDoItem - delete(): todoitem - does not exist.");
            return false;
        }
        return true;
    }

    // TODO: UPDATE


    @Override
    public String toString() {
        return String.format("TodoItem [id=%s, text=%s, checked=%b, updatedAt=%s, createdAt=%s]", this.id, this.text, this.checked, this.createdAt, this.updatedAt);

    }
}
